# mkdocs.yml

# 项目信息
site_name: my-little-ML-book  # 替换成你的书籍名称
site_url: https://juwyang.github.io/my-ML-book/ # 如果使用 GitHub Pages，或者留空让 Read the Docs 自动填充
site_author: JYang
# site_description: ML from AI

# 版权信息 (可选)
copyright: 'Copyright &copy; 2025 JYang'

# 主题配置 (Read the Docs 默认主题是 "readthedocs")
theme:
  name: rtd-dropdown  # 或者 'material' 等其他主题
  # 可选配置，例如：
  # highlightjs: true
  # languages: ['zh'] # 如果你的内容主要是中文

# 导航栏配置 (非常重要，用于生成左侧导航)
nav:
  - 'Preface': 'index.md'
  - 'General': 'General.md'
  - 'LinearRegression': 'LinearRegression.md'
  - 'PCA': 'PCA.md'
  - 'SVM': 'SVM.md'
  - 'Boosting': 'Boosting.md'
  - 'Warehouse': 'Warehouse.md'


# Markdown 扩展 (可选，但常用)
markdown_extensions:
  - admonition  # 用于创建提示框，如 Note, Warning 等
  - pymdownx.highlight: # 代码高亮
      anchor_linenums: true
  - pymdownx.superfences 
  - pymdownx.arithmatex:
      generic: true # 允许使用 LaTeX 数学公式
  - toc:
      permalink: true # 为标题添加永久链接
      toc_depth: 3    # 目录深度
      
extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6  # MathJax 推荐的 polyfill
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js # MathJax v3 CDN
# 插件 (可选)
# plugins:
#   - search # MkDocs 内置搜索功能，Read the Docs 也有自己的搜索

# Read the Docs 通常会覆盖 docs_dir，但本地构建时有用
# docs_dir: 'docs'